---
# See the documentation for more information:
# https://packit.dev/docs/configuration/

upstream_tag_template: v{version}

files_to_sync:
  - src: rpm/gating.yml
    dest: gating.yml
    delete: true
  - src: pyproject.toml
    dest: pyproject.toml
    delete: true
  - src: plans/
    dest: plans/
    delete: true
    mkpath: true
  - src: tests/
    dest: tests/
    delete: true
    mkpath: true
  - src: .fmf/
    dest: .fmf/
    delete: true
    mkpath: true

packages:
  python-podman-fedora:
    pkg_tool: fedpkg
    downstream_package_name: python-podman
    specfile_path: rpm/python-podman.spec
  python-podman-centos:
    pkg_tool: centpkg
    downstream_package_name: python-podman
    specfile_path: rpm/python-podman.spec
  python-podman-rhel:
    specfile_path: rpm/python-podman.spec

srpm_build_deps:
  - make

jobs:
  # Copr builds for Fedora
  - job: copr_build
    trigger: pull_request
    identifier: pr-fedora
    packages: [python-podman-fedora]
    targets:
      - fedora-all

  # Copr builds for CentOS Stream
  - job: copr_build
    trigger: pull_request
    identifier: pr-centos
    packages: [python-podman-centos]
    targets:
      - centos-stream-10
      - centos-stream-9

  # Copr builds for RHEL
  - job: copr_build
    trigger: pull_request
    identifier: pr-rhel
    packages: [python-podman-rhel]
    targets:
      - epel-9

  # Run on commit to main branch
  - job: copr_build
    trigger: commit
    identifier: commit-fedora
    packages: [python-podman-fedora]
    branch: main
    owner: rhcontainerbot
    project: podman-next

  # Downstream sync for Fedora
  - job: propose_downstream
    trigger: release
    packages: [python-podman-fedora]
    dist_git_branches:
      - fedora-all

  # Downstream sync for CentOS Stream
  # TODO: c9s enablement being tracked in https://issues.redhat.com/browse/RUN-2123
  - job: propose_downstream
    trigger: release
    packages: [python-podman-centos]
    dist_git_branches:
      - c10s
      - c9s

  - job: koji_build
    trigger: commit
    packages: [python-podman-fedora]
    dist_git_branches:
      - fedora-all

  - job: bodhi_update
    trigger: commit
    packages: [python-podman-fedora]
    dist_git_branches:
      - fedora-branched # rawhide updates are created automatically


  # Test linting on the codebase
  # This test might break based on the OS and lint used, so we follow fedora-latest as a reference
  - job: tests
    trigger: pull_request
    identifier: distro-sanity
    tmt_plan: /distro/sanity
    packages: [python-podman-fedora]
    targets:
      - fedora-latest-stable
    skip_build: true


  # test unit test coverage
  - job: tests
    trigger: pull_request
    identifier: unittest-coverage
    tmt_plan: /distro/unittest_coverage
    packages: [python-podman-fedora]
    targets:
      - fedora-latest-stable
    skip_build: true


  # TODO: test integration test coverage

  # run all tests for all python versions on all fedoras
  - job: tests
    trigger: pull_request
    identifier: distro-fedora-all
    tmt_plan: /distro/all_python
    packages: [python-podman-fedora]
    targets:
      - fedora-all

  # run tests for the rawhide python version using podman-next packages
  - job: tests
    trigger: pull_request
    identifier: podman-next-fedora-base
    tmt_plan: /pnext/base_python
    packages: [python-podman-fedora]
    targets:
      - fedora-rawhide
    tf_extra_params:
      environments:
        - artifacts:
          - type: repository-file
            id: https://copr.fedorainfracloud.org/coprs/rhcontainerbot/podman-next/repo/fedora-$releasever/rhcontainerbot-podman-next-fedora-$releasever.repo
    manual_trigger: true
    labels:
      - pnext
      - podman-next

  - job: tests
    trigger: pull_request
    identifier: distro-centos-base
    tmt_plan: /distro/base_python
    packages: [python-podman-centos]
    targets:
      - centos-stream-9
      - centos-stream-10

  - job: tests
    trigger: pull_request
    identifier: distro-rhel-base
    tmt_plan: /distro/base_python
    packages: [python-podman-rhel]
    targets:
      - epel-9
