name: Test Build Python distribution 📦

on:
  pull_request:

permissions: {}

jobs:
  build:
    name: Test Build Python distribution 📦
    runs-on: ubuntu-latest
    environment:
      name: build
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
        with:
          persist-credentials: false

      - name: Build Python package
        uses: ./.github/actions/build-python-package
